# Generated by Django 4.2.7 on 2023-11-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
